name: release charts ci

on:
  push:
    branches: ['**']
    paths:
      - "pom.xml"
      - ".github/workflows/actions/action.yaml"
      - "k8s/charts/**"
      - ".github/workflows/charts-ci.yaml"
      - ".github/workflows/gitleak/action.yaml"
      - "gitleaks.toml"
  pull_request:
    branches: ['**']
    paths:
      - "pom.xml"
      - ".github/workflows/actions/action.yaml"
      - "k8s/charts/**"
      - ".github/workflows/charts-ci.yaml"
      - ".github/workflows/gitleak/action.yaml"
      - "gitleaks.toml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fake build (charts)
        run: |
          echo "Charts do not require a build step."
          echo "Build job completed."
