name: release charts ci

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fake build (charts)
        run: |
          echo "Charts do not require a build step."
          echo "Build job completed."

